### ISSUE TITLE
GitHub Action Test CANNOT PASS

### ISSUE THREAD

**Issue by DrEden33773** [DrEden33773/learning-rvemu-for-book#1]
Issue is on the title. 

Everything is normal on my WSL2(with ubuntu 23.01). 

Is there anyone who could lend me a hand for help?

**Comment by Banyc** [comment]
My speculation: there is no `llvm-objcopy` in the GitHub Actions machine.

**Comment by DrEden33773** [comment]
> My speculation: there is no `llvm-objcopy` in the GitHub Actions machine.
> 

Roger that, I'll turn into `Docker` with the minimum copy of my offline environment. Thanks!

**Comment by DrEden33773** [comment]
> My speculation: there is no `llvm-objcopy` in the GitHub Actions machine.

What an `excellent` prediction, bro! I'd love to express my sincere thankfulness to you!

Here's what I've done:

First, create a `DockerFile`, which needs to be set as follows:

1. install `build-essentials, rustup, llvm-dev, clang, lld`
2. set `lld` as the default linker
3. set other environment variables properly
4. cargo build && cargo test

Then, let the `GitHub Actions` build and run the container via `docker`

In the end, I'll attach all of the critical files in need:

Dockerfile:

```Dockerfile
FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get install -y curl && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    . $HOME/.cargo/env && \
    apt-get install -y llvm-dev clang lld && \
    update-alternatives --install /usr/bin/ld ld /usr/bin/lld 100 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY . .

RUN cargo build && cargo test

CMD ["cargo", "test"]
```

`GitHub Actions` config:

```yml
name: Rust with LLVM via Docker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          docker build -t my-rust-app .
          docker run my-rust-app
```

Again, thanks so much! Have a nice day!
